---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pacman-secret
  namespace: default
spec:
  encryptedData:
    pass: AgCR3D6apG12zIPtH4nF+ADKvfTXT/JPPuYUGJYnNWRmjk6gSesYBJuRBz1WeP65/xiIiKiQFwdYS9T/vRdlJc6ueoIpXAwQPWrB/GD6oN72oczechyhURfpUK9bCw1AzK4tY899BRuayfO80+daK1XpA9SNsGod1WyQsd7UE8jY3TdUBuGm9lmJc5zUfZW+fXDE+79aBHrc79uaqNl33e010JETdtw7KADAL6NNeijVJAlK+PkpIlCO42Yt23w27P3yMVIHfVhY9e5XMuQUCeWiXm5FE6/fUlPA3tB1hs+SmRsX/6myi2OIiN6FdI1D1o2aqgrGG47uuCKHOn7dCXeaIshR/NMKS6fz9yZLMp9yzYZvZtoVx+XROXZJlYnEhIbBsRs8gzW5GosGp4fVydBsEhUu3cZQpM8AcNFG64sAU1aq5Df8xxpY/YGwz4MHrI5pFFEmUZJy58gwS4ITQFOIIVrCMwxT5ou9uVxE9iZQ5sxtA4MFlp9LOfb5EqlqLLsNFa+zxkvb7M4/YkKBxYucn+un5aHicbxTj1Ks/yrPRuxQLG2pMJtvqF5ORJp6SAoov0UjTbDYEbZyRcyTyM8tkh88UenkhJtAxA/Kwe3iJqGUcm8iZobiU4GJv4jKlz3jlxEk/fOhJ+k0mePvT7W9N2CAKaLd+Uw7rEgPCToC6VDFxnCV6HgdWm2/nHersFm0Uxeni2I=
    user: AgB+t1tCg6bN9B4LhwZHJqX70zFENjDde9BX95RjFaC+OEqNibFywoOmd6dN+uAt15G/PBPT0Fx6ilyU9TbQs3Jk8w7HTcF1jHcXvn/m1fMynECL8jYfigMlkBpMahSF4WClTaoEP418RBUjHGPgkJx9JRQVX3w1UHHocEEFTXH9jkeuTSSGn9JfXtywDIhWp+2yBGUWl3lRj7Vu1qB/M3PNownRD7t+H5Zllh+Vv5scfLhr0md3ztCnOQyVKIllKCM/9MaoCIFQ4nROHOxnn9yNoAHEZXSH/kX6d5fLbhm52uXdJ6bJ7bGsnG1M7zw5Wmah/YejAsBqbw+Fy57OXe5Uk4h5jbk7gB+GrkcQgdu8cTgxo1OOvGT3CpZWPAXNhoyx3lu7TAYbSI/FpppDsH6y+6eHqrhYPJRIw0TbKj8YhQ1GiEfsWiDczi2dvagGsingOsktDbK3PJPB37cgsESdTyMUgpzDft3mihAtycJUVi495Nb4O9RtiF6ArtAMzCBuhF9yUVaq6KjQcfXVM39ep9qPlnqlP+BSl722GjNAbOyo74H87SAo403gq9MOB3XBI2G3LxBh0LGzyyfqXGsa7lYkPFi0iGkAO32ZSY3LtT8NatorEEjjc34dP/7nvEZPxi6g8ob7UoMnF52PhM/arpAY9qm/oUAajMXiWBqA20ZRyllF+ZANSw8EwGbaqdfWFYvoT2s=
  template:
    metadata:
      name: pacman-secret
      namespace: default
    type: Opaque
